version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: deciduous
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    ports:
      - 3306:3306
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

  adminer:
    image: adminer
    ports:
      - 33060:8080

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - 8081:8081
