version: '3.7'

services:
  mariadb:
    container_name: deciduous_mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    ports:
      - 3306:3306
  adminer:
    container_name: deciduous_adminer
    image: adminer
    restart: always
    ports:
      - 33060:8080
  redis:
    container_name: deciduous_redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
